/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_imskpe_main (void)
{
  GtkWidget *imskpe_main;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem3;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *hbox2;
  GtkWidget *toolbar1;
  GtkWidget *bn_quit;
  GtkWidget *bn_open;
  GtkWidget *toolbar2;
  GtkWidget *bn_move;
  GtkWidget *bn_insert;
  GtkWidget *bn_delete;
  GtkWidget *hbox1;
  GtkWidget *vbox2;
  GtkWidget *nb_buttons;
  GtkWidget *table14;
  GtkWidget *lb_g_du;
  GtkWidget *lb_msec1;
  GtkWidget *label3;
  GtkWidget *lb_g_ui;
  GtkWidget *lb_g_sr;
  GtkWidget *lb_g_nf;
  GtkWidget *lb_g_vs;
  GtkWidget *lb_g_cp;
  GtkWidget *lb_samp1;
  GtkObject *spbn_numF_adj;
  GtkWidget *spbn_numF;
  GtkWidget *cm_voicesource;
  GList *cm_voicesource_items = NULL;
  GtkWidget *cm_vs_entry;
  GtkWidget *cm_cascpar;
  GList *cm_cascpar_items = NULL;
  GtkWidget *cm_cp_entry;
  GtkObject *spbn_sprate_adj;
  GtkWidget *spbn_sprate;
  GtkObject *spbn_ui_adj;
  GtkWidget *spbn_ui;
  GtkObject *spbn_duration_adj;
  GtkWidget *spbn_duration;
  GtkWidget *lb_global;
  GtkWidget *nb_resonators;
  GtkWidget *tbl_f1;
  GtkWidget *bn_f1_color;
  GtkWidget *bn_f1_freq;
  GtkWidget *bn_f1_amp;
  GtkWidget *bn_f1_band;
  GtkWidget *bn_f1_bandp;
  GtkWidget *lb_f1;
  GtkWidget *tbl_f2;
  GtkWidget *bn_f2_color;
  GtkWidget *bn_f2_freq;
  GtkWidget *bn_f2_amp;
  GtkWidget *bn_f2_band;
  GtkWidget *bn_f2_bandp;
  GtkWidget *lb_f2;
  GtkWidget *tbl_f3;
  GtkWidget *bn_f3_color;
  GtkWidget *bn_f3_freq;
  GtkWidget *bn_f3_amp;
  GtkWidget *bn_f3_band;
  GtkWidget *bn_f3_bandp;
  GtkWidget *lb_f3;
  GtkWidget *tbl_f4;
  GtkWidget *bn_f4_color;
  GtkWidget *bn_f4_freq;
  GtkWidget *bn_f4_amp;
  GtkWidget *bn_f4_band;
  GtkWidget *bn_f4_bandp;
  GtkWidget *lb_f4;
  GtkWidget *tbl_f5;
  GtkWidget *bn_f5_color;
  GtkWidget *bn_f5_freq;
  GtkWidget *bn_f5_amp;
  GtkWidget *bn_f5_band;
  GtkWidget *bn_f5_bandp;
  GtkWidget *lb_f5;
  GtkWidget *tbl_f6;
  GtkWidget *bn_f6_color;
  GtkWidget *bn_f6_freq;
  GtkWidget *bn_f6_amp;
  GtkWidget *bn_f6_band;
  GtkWidget *bn_f6_bandp;
  GtkWidget *lb_f6;
  GtkWidget *tbl_nasal;
  GtkWidget *bn_nasal_color;
  GtkWidget *bn_nasal_z_freq;
  GtkWidget *bn_nasal_z_band;
  GtkWidget *bn_nasal_p_freq;
  GtkWidget *bn_nasal_p_band;
  GtkWidget *bn_nasal_p_amp;
  GtkWidget *lb_nasals;
  GtkWidget *lb_resonators;
  GtkWidget *table15;
  GtkWidget *bn_vs_gopenquot;
  GtkWidget *bn_vs_breath;
  GtkWidget *bn_vs_spectilt;
  GtkWidget *bn_vs_skewness;
  GtkWidget *bn_vs_fundfreq;
  GtkWidget *lb_voice;
  GtkWidget *table16;
  GtkWidget *bn_examp_voice;
  GtkWidget *bn_examp_asp;
  GtkWidget *bn_examp_fric;
  GtkWidget *bn_examp_bypass;
  GtkWidget *bn_examp_voicepar;
  GtkWidget *bn_examp_siggain;
  GtkWidget *lb_exc_amp;
  GtkWidget *table17;
  GtkWidget *vbox3;
  GtkWidget *nb_draw;
  GtkWidget *draw_freq;
  GtkWidget *lb_draw_freq;
  GtkWidget *draw_amp;
  GtkWidget *lb_draw_amp;
  GtkWidget *draw_band;
  GtkWidget *lb_draw_band;
  GtkWidget *hbox3;
  GtkWidget *sb_file;
  GtkWidget *sb_add;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  imskpe_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (imskpe_main), _("IMSKPE"));
  gtk_window_set_default_size (GTK_WINDOW (imskpe_main), 600, 400);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (imskpe_main), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save_as1);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (hbox2), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);

  bn_quit = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-quit",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_show (bn_quit);

  bn_open = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-open",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_show (bn_open);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_box_pack_end (GTK_BOX (hbox2), toolbar2, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);

  bn_move = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("move"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (bn_move);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (bn_move), TRUE);

  bn_insert = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("insert"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (bn_insert);

  bn_delete = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("delete"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (bn_delete);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, FALSE, TRUE, 0);

  nb_buttons = gtk_notebook_new ();
  gtk_widget_show (nb_buttons);
  gtk_box_pack_start (GTK_BOX (vbox2), nb_buttons, FALSE, TRUE, 0);

  table14 = gtk_table_new (6, 3, FALSE);
  gtk_widget_show (table14);
  gtk_container_add (GTK_CONTAINER (nb_buttons), table14);

  lb_g_du = gtk_label_new (_("duration: "));
  gtk_widget_show (lb_g_du);
  gtk_table_attach (GTK_TABLE (table14), lb_g_du, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lb_g_du), 0, 0.5);

  lb_msec1 = gtk_label_new (_("msec"));
  gtk_widget_show (lb_msec1);
  gtk_table_attach (GTK_TABLE (table14), lb_msec1, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lb_msec1), 0, 0.5);

  label3 = gtk_label_new (_("msec"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table14), label3, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  lb_g_ui = gtk_label_new (_("update interval: "));
  gtk_widget_show (lb_g_ui);
  gtk_table_attach (GTK_TABLE (table14), lb_g_ui, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lb_g_ui), 0, 0.5);

  lb_g_sr = gtk_label_new (_("sampling rate: "));
  gtk_widget_show (lb_g_sr);
  gtk_table_attach (GTK_TABLE (table14), lb_g_sr, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lb_g_sr), 0, 0.5);

  lb_g_nf = gtk_label_new (_("Num of formants: "));
  gtk_widget_show (lb_g_nf);
  gtk_table_attach (GTK_TABLE (table14), lb_g_nf, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lb_g_nf), 0, 0.5);

  lb_g_vs = gtk_label_new (_("voice source: "));
  gtk_widget_show (lb_g_vs);
  gtk_table_attach (GTK_TABLE (table14), lb_g_vs, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lb_g_vs), 0, 0.5);

  lb_g_cp = gtk_label_new (_("branches"));
  gtk_widget_show (lb_g_cp);
  gtk_table_attach (GTK_TABLE (table14), lb_g_cp, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lb_g_cp), 0, 0.5);

  lb_samp1 = gtk_label_new (_("samp/sec"));
  gtk_widget_show (lb_samp1);
  gtk_table_attach (GTK_TABLE (table14), lb_samp1, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lb_samp1), 0, 0.5);

  spbn_numF_adj = gtk_adjustment_new (6, 1, 6, 1, 1, 1);
  spbn_numF = gtk_spin_button_new (GTK_ADJUSTMENT (spbn_numF_adj), 1, 0);
  gtk_widget_show (spbn_numF);
  gtk_table_attach (GTK_TABLE (table14), spbn_numF, 1, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spbn_numF), GTK_UPDATE_IF_VALID);

  cm_voicesource = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (cm_voicesource)->popwin),
                     "GladeParentKey", cm_voicesource);
  gtk_widget_show (cm_voicesource);
  gtk_table_attach (GTK_TABLE (table14), cm_voicesource, 1, 3, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  cm_voicesource_items = g_list_append (cm_voicesource_items, (gpointer) _("impulse"));
  cm_voicesource_items = g_list_append (cm_voicesource_items, (gpointer) _("natural"));
  cm_voicesource_items = g_list_append (cm_voicesource_items, (gpointer) _("sampled"));
  gtk_combo_set_popdown_strings (GTK_COMBO (cm_voicesource), cm_voicesource_items);
  g_list_free (cm_voicesource_items);

  cm_vs_entry = GTK_COMBO (cm_voicesource)->entry;
  gtk_widget_show (cm_vs_entry);

  cm_cascpar = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (cm_cascpar)->popwin),
                     "GladeParentKey", cm_cascpar);
  gtk_widget_show (cm_cascpar);
  gtk_table_attach (GTK_TABLE (table14), cm_cascpar, 1, 3, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  cm_cascpar_items = g_list_append (cm_cascpar_items, (gpointer) _("cascade + parallel"));
  cm_cascpar_items = g_list_append (cm_cascpar_items, (gpointer) _("parallel only"));
  gtk_combo_set_popdown_strings (GTK_COMBO (cm_cascpar), cm_cascpar_items);
  g_list_free (cm_cascpar_items);

  cm_cp_entry = GTK_COMBO (cm_cascpar)->entry;
  gtk_widget_show (cm_cp_entry);

  spbn_sprate_adj = gtk_adjustment_new (16000, 5000, 24000, 100, 1000, 1000);
  spbn_sprate = gtk_spin_button_new (GTK_ADJUSTMENT (spbn_sprate_adj), 1, 0);
  gtk_widget_show (spbn_sprate);
  gtk_table_attach (GTK_TABLE (table14), spbn_sprate, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spbn_sprate), TRUE);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spbn_sprate), GTK_UPDATE_IF_VALID);

  spbn_ui_adj = gtk_adjustment_new (10, 2, 20, 1, 10, 10);
  spbn_ui = gtk_spin_button_new (GTK_ADJUSTMENT (spbn_ui_adj), 1, 0);
  gtk_widget_show (spbn_ui);
  gtk_table_attach (GTK_TABLE (table14), spbn_ui, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spbn_ui), TRUE);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spbn_ui), GTK_UPDATE_IF_VALID);

  spbn_duration_adj = gtk_adjustment_new (500, 30, 5000, 10, 100, 100);
  spbn_duration = gtk_spin_button_new (GTK_ADJUSTMENT (spbn_duration_adj), 1, 0);
  gtk_widget_show (spbn_duration);
  gtk_table_attach (GTK_TABLE (table14), spbn_duration, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spbn_duration), TRUE);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spbn_duration), GTK_UPDATE_IF_VALID);

  lb_global = gtk_label_new (_("global"));
  gtk_widget_show (lb_global);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_buttons), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_buttons), 0), lb_global);

  nb_resonators = gtk_notebook_new ();
  gtk_widget_show (nb_resonators);
  gtk_container_add (GTK_CONTAINER (nb_buttons), nb_resonators);

  tbl_f1 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (tbl_f1);
  gtk_container_add (GTK_CONTAINER (nb_resonators), tbl_f1);

  bn_f1_color = gtk_button_new_from_stock ("gtk-select-color");
  gtk_widget_show (bn_f1_color);
  gtk_table_attach (GTK_TABLE (tbl_f1), bn_f1_color, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f1_freq = gtk_toggle_button_new_with_mnemonic (_("frequencies"));
  gtk_widget_show (bn_f1_freq);
  gtk_table_attach (GTK_TABLE (tbl_f1), bn_f1_freq, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f1_amp = gtk_toggle_button_new_with_mnemonic (_("amplitudes"));
  gtk_widget_show (bn_f1_amp);
  gtk_table_attach (GTK_TABLE (tbl_f1), bn_f1_amp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f1_band = gtk_toggle_button_new_with_mnemonic (_("bandwidth"));
  gtk_widget_show (bn_f1_band);
  gtk_table_attach (GTK_TABLE (tbl_f1), bn_f1_band, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f1_bandp = gtk_toggle_button_new_with_mnemonic (_("bandwidth parallel"));
  gtk_widget_show (bn_f1_bandp);
  gtk_table_attach (GTK_TABLE (tbl_f1), bn_f1_bandp, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_f1 = gtk_label_new (_("F1"));
  gtk_widget_show (lb_f1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_resonators), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_resonators), 0), lb_f1);
  gtk_label_set_use_markup (GTK_LABEL (lb_f1), TRUE);

  tbl_f2 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (tbl_f2);
  gtk_container_add (GTK_CONTAINER (nb_resonators), tbl_f2);

  bn_f2_color = gtk_button_new_from_stock ("gtk-select-color");
  gtk_widget_show (bn_f2_color);
  gtk_table_attach (GTK_TABLE (tbl_f2), bn_f2_color, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f2_freq = gtk_toggle_button_new_with_mnemonic (_("frequencies"));
  gtk_widget_show (bn_f2_freq);
  gtk_table_attach (GTK_TABLE (tbl_f2), bn_f2_freq, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f2_amp = gtk_toggle_button_new_with_mnemonic (_("amplitudes"));
  gtk_widget_show (bn_f2_amp);
  gtk_table_attach (GTK_TABLE (tbl_f2), bn_f2_amp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f2_band = gtk_toggle_button_new_with_mnemonic (_("bandwidth"));
  gtk_widget_show (bn_f2_band);
  gtk_table_attach (GTK_TABLE (tbl_f2), bn_f2_band, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f2_bandp = gtk_toggle_button_new_with_mnemonic (_("bandwidth parallel"));
  gtk_widget_show (bn_f2_bandp);
  gtk_table_attach (GTK_TABLE (tbl_f2), bn_f2_bandp, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_f2 = gtk_label_new (_("F2"));
  gtk_widget_show (lb_f2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_resonators), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_resonators), 1), lb_f2);

  tbl_f3 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (tbl_f3);
  gtk_container_add (GTK_CONTAINER (nb_resonators), tbl_f3);

  bn_f3_color = gtk_button_new_from_stock ("gtk-select-color");
  gtk_widget_show (bn_f3_color);
  gtk_table_attach (GTK_TABLE (tbl_f3), bn_f3_color, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f3_freq = gtk_toggle_button_new_with_mnemonic (_("frequencies"));
  gtk_widget_show (bn_f3_freq);
  gtk_table_attach (GTK_TABLE (tbl_f3), bn_f3_freq, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f3_amp = gtk_toggle_button_new_with_mnemonic (_("amplitudes"));
  gtk_widget_show (bn_f3_amp);
  gtk_table_attach (GTK_TABLE (tbl_f3), bn_f3_amp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f3_band = gtk_toggle_button_new_with_mnemonic (_("bandwidth"));
  gtk_widget_show (bn_f3_band);
  gtk_table_attach (GTK_TABLE (tbl_f3), bn_f3_band, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f3_bandp = gtk_toggle_button_new_with_mnemonic (_("bandwidth parallel"));
  gtk_widget_show (bn_f3_bandp);
  gtk_table_attach (GTK_TABLE (tbl_f3), bn_f3_bandp, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_f3 = gtk_label_new (_("F3"));
  gtk_widget_show (lb_f3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_resonators), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_resonators), 2), lb_f3);

  tbl_f4 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (tbl_f4);
  gtk_container_add (GTK_CONTAINER (nb_resonators), tbl_f4);

  bn_f4_color = gtk_button_new_from_stock ("gtk-select-color");
  gtk_widget_show (bn_f4_color);
  gtk_table_attach (GTK_TABLE (tbl_f4), bn_f4_color, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f4_freq = gtk_toggle_button_new_with_mnemonic (_("frequencies"));
  gtk_widget_show (bn_f4_freq);
  gtk_table_attach (GTK_TABLE (tbl_f4), bn_f4_freq, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f4_amp = gtk_toggle_button_new_with_mnemonic (_("amplitudes"));
  gtk_widget_show (bn_f4_amp);
  gtk_table_attach (GTK_TABLE (tbl_f4), bn_f4_amp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f4_band = gtk_toggle_button_new_with_mnemonic (_("bandwidth"));
  gtk_widget_show (bn_f4_band);
  gtk_table_attach (GTK_TABLE (tbl_f4), bn_f4_band, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f4_bandp = gtk_toggle_button_new_with_mnemonic (_("bandwidth parallel"));
  gtk_widget_show (bn_f4_bandp);
  gtk_table_attach (GTK_TABLE (tbl_f4), bn_f4_bandp, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_f4 = gtk_label_new (_("F4"));
  gtk_widget_show (lb_f4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_resonators), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_resonators), 3), lb_f4);

  tbl_f5 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (tbl_f5);
  gtk_container_add (GTK_CONTAINER (nb_resonators), tbl_f5);

  bn_f5_color = gtk_button_new_from_stock ("gtk-select-color");
  gtk_widget_show (bn_f5_color);
  gtk_table_attach (GTK_TABLE (tbl_f5), bn_f5_color, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f5_freq = gtk_toggle_button_new_with_mnemonic (_("frequencies"));
  gtk_widget_show (bn_f5_freq);
  gtk_table_attach (GTK_TABLE (tbl_f5), bn_f5_freq, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f5_amp = gtk_toggle_button_new_with_mnemonic (_("amplitudes"));
  gtk_widget_show (bn_f5_amp);
  gtk_table_attach (GTK_TABLE (tbl_f5), bn_f5_amp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f5_band = gtk_toggle_button_new_with_mnemonic (_("bandwidth"));
  gtk_widget_show (bn_f5_band);
  gtk_table_attach (GTK_TABLE (tbl_f5), bn_f5_band, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f5_bandp = gtk_toggle_button_new_with_mnemonic (_("bandwidth parallel"));
  gtk_widget_show (bn_f5_bandp);
  gtk_table_attach (GTK_TABLE (tbl_f5), bn_f5_bandp, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_f5 = gtk_label_new (_("F5"));
  gtk_widget_show (lb_f5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_resonators), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_resonators), 4), lb_f5);

  tbl_f6 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (tbl_f6);
  gtk_container_add (GTK_CONTAINER (nb_resonators), tbl_f6);

  bn_f6_color = gtk_button_new_from_stock ("gtk-select-color");
  gtk_widget_show (bn_f6_color);
  gtk_table_attach (GTK_TABLE (tbl_f6), bn_f6_color, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f6_freq = gtk_toggle_button_new_with_mnemonic (_("frequencies"));
  gtk_widget_show (bn_f6_freq);
  gtk_table_attach (GTK_TABLE (tbl_f6), bn_f6_freq, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f6_amp = gtk_toggle_button_new_with_mnemonic (_("amplitudes"));
  gtk_widget_show (bn_f6_amp);
  gtk_table_attach (GTK_TABLE (tbl_f6), bn_f6_amp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f6_band = gtk_toggle_button_new_with_mnemonic (_("bandwidth"));
  gtk_widget_show (bn_f6_band);
  gtk_table_attach (GTK_TABLE (tbl_f6), bn_f6_band, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_f6_bandp = gtk_toggle_button_new_with_mnemonic (_("bandwidth parallel"));
  gtk_widget_show (bn_f6_bandp);
  gtk_table_attach (GTK_TABLE (tbl_f6), bn_f6_bandp, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_f6 = gtk_label_new (_("F6"));
  gtk_widget_show (lb_f6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_resonators), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_resonators), 5), lb_f6);

  tbl_nasal = gtk_table_new (5, 3, FALSE);
  gtk_widget_show (tbl_nasal);
  gtk_container_add (GTK_CONTAINER (nb_resonators), tbl_nasal);

  bn_nasal_color = gtk_button_new_from_stock ("gtk-select-color");
  gtk_widget_show (bn_nasal_color);
  gtk_table_attach (GTK_TABLE (tbl_nasal), bn_nasal_color, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_nasal_z_freq = gtk_toggle_button_new_with_mnemonic (_("zero frequencies"));
  gtk_widget_show (bn_nasal_z_freq);
  gtk_table_attach (GTK_TABLE (tbl_nasal), bn_nasal_z_freq, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_nasal_z_band = gtk_toggle_button_new_with_mnemonic (_("zero bandwidth"));
  gtk_widget_show (bn_nasal_z_band);
  gtk_table_attach (GTK_TABLE (tbl_nasal), bn_nasal_z_band, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_nasal_p_freq = gtk_toggle_button_new_with_mnemonic (_("pole frequency"));
  gtk_widget_show (bn_nasal_p_freq);
  gtk_table_attach (GTK_TABLE (tbl_nasal), bn_nasal_p_freq, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_nasal_p_band = gtk_toggle_button_new_with_mnemonic (_("pole bandwidth"));
  gtk_widget_show (bn_nasal_p_band);
  gtk_table_attach (GTK_TABLE (tbl_nasal), bn_nasal_p_band, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_nasal_p_amp = gtk_toggle_button_new_with_mnemonic (_("pole amplitude"));
  gtk_widget_show (bn_nasal_p_amp);
  gtk_table_attach (GTK_TABLE (tbl_nasal), bn_nasal_p_amp, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_nasals = gtk_label_new (_("nasals"));
  gtk_widget_show (lb_nasals);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_resonators), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_resonators), 6), lb_nasals);

  lb_resonators = gtk_label_new (_("resonators"));
  gtk_widget_show (lb_resonators);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_buttons), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_buttons), 1), lb_resonators);

  table15 = gtk_table_new (5, 3, FALSE);
  gtk_widget_show (table15);
  gtk_container_add (GTK_CONTAINER (nb_buttons), table15);

  bn_vs_gopenquot = gtk_toggle_button_new_with_mnemonic (_("glottal open quotient"));
  gtk_widget_show (bn_vs_gopenquot);
  gtk_table_attach (GTK_TABLE (table15), bn_vs_gopenquot, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_vs_breath = gtk_toggle_button_new_with_mnemonic (_("breathiness"));
  gtk_widget_show (bn_vs_breath);
  gtk_table_attach (GTK_TABLE (table15), bn_vs_breath, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_vs_spectilt = gtk_toggle_button_new_with_mnemonic (_("spectral tilt"));
  gtk_widget_show (bn_vs_spectilt);
  gtk_table_attach (GTK_TABLE (table15), bn_vs_spectilt, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_vs_skewness = gtk_toggle_button_new_with_mnemonic (_("skewness"));
  gtk_widget_show (bn_vs_skewness);
  gtk_table_attach (GTK_TABLE (table15), bn_vs_skewness, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, bn_vs_skewness, _("skewness (speed quotient) of voiced excitation signal"), NULL);

  bn_vs_fundfreq = gtk_toggle_button_new_with_mnemonic (_("fundamental frequency"));
  gtk_widget_show (bn_vs_fundfreq);
  gtk_table_attach (GTK_TABLE (table15), bn_vs_fundfreq, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_voice = gtk_label_new (_("voice src"));
  gtk_widget_show (lb_voice);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_buttons), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_buttons), 2), lb_voice);

  table16 = gtk_table_new (6, 3, FALSE);
  gtk_widget_show (table16);
  gtk_container_add (GTK_CONTAINER (nb_buttons), table16);

  bn_examp_voice = gtk_toggle_button_new_with_mnemonic (_("amp. of voicing"));
  gtk_widget_show (bn_examp_voice);
  gtk_table_attach (GTK_TABLE (table16), bn_examp_voice, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_examp_asp = gtk_toggle_button_new_with_mnemonic (_("amp. of aspiration"));
  gtk_widget_show (bn_examp_asp);
  gtk_table_attach (GTK_TABLE (table16), bn_examp_asp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_examp_fric = gtk_toggle_button_new_with_mnemonic (_("amp. of frication"));
  gtk_widget_show (bn_examp_fric);
  gtk_table_attach (GTK_TABLE (table16), bn_examp_fric, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bn_examp_bypass = gtk_toggle_button_new_with_mnemonic (_("amp. of bypass path (par)"));
  gtk_widget_show (bn_examp_bypass);
  gtk_table_attach (GTK_TABLE (table16), bn_examp_bypass, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, bn_examp_bypass, _("amplitude of bypass path (parallel branch)"), NULL);

  bn_examp_voicepar = gtk_toggle_button_new_with_mnemonic (_("amp. of voicing (par)"));
  gtk_widget_show (bn_examp_voicepar);
  gtk_table_attach (GTK_TABLE (table16), bn_examp_voicepar, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, bn_examp_voicepar, _("amplitude of voicing (parallel branch)"), NULL);

  bn_examp_siggain = gtk_toggle_button_new_with_mnemonic (_("overall signal gain"));
  gtk_widget_show (bn_examp_siggain);
  gtk_table_attach (GTK_TABLE (table16), bn_examp_siggain, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lb_exc_amp = gtk_label_new (_("exc. amp."));
  gtk_widget_show (lb_exc_amp);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_buttons), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_buttons), 3), lb_exc_amp);

  table17 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table17);
  gtk_box_pack_start (GTK_BOX (vbox2), table17, FALSE, FALSE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox3, TRUE, TRUE, 0);

  nb_draw = gtk_notebook_new ();
  gtk_widget_show (nb_draw);
  gtk_box_pack_start (GTK_BOX (vbox3), nb_draw, TRUE, TRUE, 0);

  draw_freq = gtk_drawing_area_new ();
  gtk_widget_show (draw_freq);
  gtk_container_add (GTK_CONTAINER (nb_draw), draw_freq);
  gtk_widget_set_events (draw_freq, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_LEAVE_NOTIFY_MASK);

  lb_draw_freq = gtk_label_new (_("frequencies"));
  gtk_widget_show (lb_draw_freq);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_draw), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_draw), 0), lb_draw_freq);

  draw_amp = gtk_drawing_area_new ();
  gtk_widget_show (draw_amp);
  gtk_container_add (GTK_CONTAINER (nb_draw), draw_amp);
  gtk_widget_set_events (draw_amp, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_LEAVE_NOTIFY_MASK);

  lb_draw_amp = gtk_label_new (_("amplitude"));
  gtk_widget_show (lb_draw_amp);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_draw), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_draw), 1), lb_draw_amp);

  draw_band = gtk_drawing_area_new ();
  gtk_widget_show (draw_band);
  gtk_container_add (GTK_CONTAINER (nb_draw), draw_band);
  gtk_widget_set_events (draw_band, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_LEAVE_NOTIFY_MASK);

  lb_draw_band = gtk_label_new (_("bandwidths"));
  gtk_widget_show (lb_draw_band);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nb_draw), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nb_draw), 2), lb_draw_band);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, FALSE, FALSE, 0);

  sb_file = gtk_statusbar_new ();
  gtk_widget_show (sb_file);
  gtk_box_pack_start (GTK_BOX (hbox3), sb_file, TRUE, TRUE, 0);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (sb_file), FALSE);

  sb_add = gtk_statusbar_new ();
  gtk_widget_show (sb_add);
  gtk_box_pack_start (GTK_BOX (hbox3), sb_add, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) imskpe_main, "delete_event",
                    G_CALLBACK (imskpe_quit),
                    NULL);
  g_signal_connect ((gpointer) imskpe_main, "activate_default",
                    G_CALLBACK (on_imskpe_main_activate_default),
                    NULL);
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (imskpe_quit),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) bn_quit, "clicked",
                    G_CALLBACK (imskpe_quit),
                    NULL);
  g_signal_connect ((gpointer) bn_open, "clicked",
                    G_CALLBACK (on_bn_open_clicked),
                    NULL);
  g_signal_connect ((gpointer) bn_move, "toggled",
                    G_CALLBACK (on_bn_move_toggled),
                    NULL);
  g_signal_connect ((gpointer) bn_insert, "toggled",
                    G_CALLBACK (on_bn_insert_toggled),
                    NULL);
  g_signal_connect ((gpointer) bn_delete, "toggled",
                    G_CALLBACK (on_bn_delete_toggled),
                    NULL);
  g_signal_connect ((gpointer) spbn_numF, "value_changed",
                    G_CALLBACK (on_spbn_numF_changed),
                    NULL);
  g_signal_connect ((gpointer) spbn_duration, "changed",
                    G_CALLBACK (on_spbn_duration_changed),
                    NULL);
  g_signal_connect ((gpointer) spbn_duration, "value_changed",
                    G_CALLBACK (on_spbn_duration_changed),
                    NULL);
  g_signal_connect ((gpointer) bn_f1_color, "clicked",
                    G_CALLBACK (on_bn_fX_color_clicked),
                    NULL);
  g_signal_connect ((gpointer) bn_f1_freq, "toggled",
                    G_CALLBACK (on_bn_f1_freq_toggled),
                    NULL);
  g_signal_connect ((gpointer) lb_f1, "realize",
                    G_CALLBACK (on_lb_f1_realize),
                    NULL);
  g_signal_connect ((gpointer) bn_f2_color, "clicked",
                    G_CALLBACK (on_bn_fX_color_clicked),
                    NULL);
  g_signal_connect ((gpointer) lb_f2, "realize",
                    G_CALLBACK (on_lb_f2_realize),
                    NULL);
  g_signal_connect ((gpointer) bn_f3_color, "clicked",
                    G_CALLBACK (on_bn_fX_color_clicked),
                    NULL);
  g_signal_connect ((gpointer) lb_f3, "realize",
                    G_CALLBACK (on_lb_f3_realize),
                    NULL);
  g_signal_connect ((gpointer) bn_f4_color, "clicked",
                    G_CALLBACK (on_bn_fX_color_clicked),
                    NULL);
  g_signal_connect ((gpointer) lb_f4, "realize",
                    G_CALLBACK (on_lb_f4_realize),
                    NULL);
  g_signal_connect ((gpointer) bn_f5_color, "clicked",
                    G_CALLBACK (on_bn_fX_color_clicked),
                    NULL);
  g_signal_connect ((gpointer) lb_f5, "realize",
                    G_CALLBACK (on_lb_f5_realize),
                    NULL);
  g_signal_connect ((gpointer) bn_f6_color, "clicked",
                    G_CALLBACK (on_bn_fX_color_clicked),
                    NULL);
  g_signal_connect ((gpointer) lb_f6, "realize",
                    G_CALLBACK (on_lb_f6_realize),
                    NULL);
  g_signal_connect ((gpointer) bn_nasal_color, "clicked",
                    G_CALLBACK (on_bn_fX_color_clicked),
                    NULL);
  g_signal_connect ((gpointer) lb_nasals, "realize",
                    G_CALLBACK (on_lb_nasals_realize),
                    NULL);
  g_signal_connect ((gpointer) nb_draw, "switch_page",
                    G_CALLBACK (on_nb_draw_switch_page),
                    NULL);
  g_signal_connect ((gpointer) draw_freq, "configure_event",
                    G_CALLBACK (on_draw_freq_configure_event),
                    NULL);
  g_signal_connect ((gpointer) draw_freq, "expose_event",
                    G_CALLBACK (on_draw_freq_expose_event),
                    NULL);
  g_signal_connect ((gpointer) draw_freq, "motion_notify_event",
                    G_CALLBACK (on_draw_freq_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) draw_amp, "motion_notify_event",
                    G_CALLBACK (on_draw_amp_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) draw_amp, "configure_event",
                    G_CALLBACK (on_draw_amp_configure_event),
                    NULL);
  g_signal_connect ((gpointer) draw_amp, "expose_event",
                    G_CALLBACK (on_draw_amp_expose_event),
                    NULL);
  g_signal_connect ((gpointer) draw_band, "configure_event",
                    G_CALLBACK (on_draw_band_configure_event),
                    NULL);
  g_signal_connect ((gpointer) draw_band, "expose_event",
                    G_CALLBACK (on_draw_band_expose_event),
                    NULL);
  g_signal_connect ((gpointer) draw_band, "motion_notify_event",
                    G_CALLBACK (on_draw_band_motion_notify_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_main, imskpe_main, "imskpe_main");
  GLADE_HOOKUP_OBJECT (imskpe_main, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (imskpe_main, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (imskpe_main, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (imskpe_main, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (imskpe_main, new1, "new1");
  GLADE_HOOKUP_OBJECT (imskpe_main, open1, "open1");
  GLADE_HOOKUP_OBJECT (imskpe_main, save1, "save1");
  GLADE_HOOKUP_OBJECT (imskpe_main, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (imskpe_main, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (imskpe_main, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (imskpe_main, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (imskpe_main, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (imskpe_main, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (imskpe_main, about1, "about1");
  GLADE_HOOKUP_OBJECT (imskpe_main, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (imskpe_main, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_quit, "bn_quit");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_open, "bn_open");
  GLADE_HOOKUP_OBJECT (imskpe_main, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_move, "bn_move");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_insert, "bn_insert");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_delete, "bn_delete");
  GLADE_HOOKUP_OBJECT (imskpe_main, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (imskpe_main, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (imskpe_main, nb_buttons, "nb_buttons");
  GLADE_HOOKUP_OBJECT (imskpe_main, table14, "table14");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_g_du, "lb_g_du");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_msec1, "lb_msec1");
  GLADE_HOOKUP_OBJECT (imskpe_main, label3, "label3");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_g_ui, "lb_g_ui");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_g_sr, "lb_g_sr");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_g_nf, "lb_g_nf");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_g_vs, "lb_g_vs");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_g_cp, "lb_g_cp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_samp1, "lb_samp1");
  GLADE_HOOKUP_OBJECT (imskpe_main, spbn_numF, "spbn_numF");
  GLADE_HOOKUP_OBJECT (imskpe_main, cm_voicesource, "cm_voicesource");
  GLADE_HOOKUP_OBJECT (imskpe_main, cm_vs_entry, "cm_vs_entry");
  GLADE_HOOKUP_OBJECT (imskpe_main, cm_cascpar, "cm_cascpar");
  GLADE_HOOKUP_OBJECT (imskpe_main, cm_cp_entry, "cm_cp_entry");
  GLADE_HOOKUP_OBJECT (imskpe_main, spbn_sprate, "spbn_sprate");
  GLADE_HOOKUP_OBJECT (imskpe_main, spbn_ui, "spbn_ui");
  GLADE_HOOKUP_OBJECT (imskpe_main, spbn_duration, "spbn_duration");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_global, "lb_global");
  GLADE_HOOKUP_OBJECT (imskpe_main, nb_resonators, "nb_resonators");
  GLADE_HOOKUP_OBJECT (imskpe_main, tbl_f1, "tbl_f1");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f1_color, "bn_f1_color");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f1_freq, "bn_f1_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f1_amp, "bn_f1_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f1_band, "bn_f1_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f1_bandp, "bn_f1_bandp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_f1, "lb_f1");
  GLADE_HOOKUP_OBJECT (imskpe_main, tbl_f2, "tbl_f2");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f2_color, "bn_f2_color");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f2_freq, "bn_f2_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f2_amp, "bn_f2_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f2_band, "bn_f2_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f2_bandp, "bn_f2_bandp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_f2, "lb_f2");
  GLADE_HOOKUP_OBJECT (imskpe_main, tbl_f3, "tbl_f3");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f3_color, "bn_f3_color");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f3_freq, "bn_f3_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f3_amp, "bn_f3_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f3_band, "bn_f3_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f3_bandp, "bn_f3_bandp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_f3, "lb_f3");
  GLADE_HOOKUP_OBJECT (imskpe_main, tbl_f4, "tbl_f4");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f4_color, "bn_f4_color");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f4_freq, "bn_f4_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f4_amp, "bn_f4_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f4_band, "bn_f4_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f4_bandp, "bn_f4_bandp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_f4, "lb_f4");
  GLADE_HOOKUP_OBJECT (imskpe_main, tbl_f5, "tbl_f5");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f5_color, "bn_f5_color");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f5_freq, "bn_f5_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f5_amp, "bn_f5_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f5_band, "bn_f5_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f5_bandp, "bn_f5_bandp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_f5, "lb_f5");
  GLADE_HOOKUP_OBJECT (imskpe_main, tbl_f6, "tbl_f6");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f6_color, "bn_f6_color");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f6_freq, "bn_f6_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f6_amp, "bn_f6_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f6_band, "bn_f6_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_f6_bandp, "bn_f6_bandp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_f6, "lb_f6");
  GLADE_HOOKUP_OBJECT (imskpe_main, tbl_nasal, "tbl_nasal");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_nasal_color, "bn_nasal_color");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_nasal_z_freq, "bn_nasal_z_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_nasal_z_band, "bn_nasal_z_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_nasal_p_freq, "bn_nasal_p_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_nasal_p_band, "bn_nasal_p_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_nasal_p_amp, "bn_nasal_p_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_nasals, "lb_nasals");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_resonators, "lb_resonators");
  GLADE_HOOKUP_OBJECT (imskpe_main, table15, "table15");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_vs_gopenquot, "bn_vs_gopenquot");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_vs_breath, "bn_vs_breath");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_vs_spectilt, "bn_vs_spectilt");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_vs_skewness, "bn_vs_skewness");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_vs_fundfreq, "bn_vs_fundfreq");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_voice, "lb_voice");
  GLADE_HOOKUP_OBJECT (imskpe_main, table16, "table16");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_examp_voice, "bn_examp_voice");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_examp_asp, "bn_examp_asp");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_examp_fric, "bn_examp_fric");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_examp_bypass, "bn_examp_bypass");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_examp_voicepar, "bn_examp_voicepar");
  GLADE_HOOKUP_OBJECT (imskpe_main, bn_examp_siggain, "bn_examp_siggain");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_exc_amp, "lb_exc_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, table17, "table17");
  GLADE_HOOKUP_OBJECT (imskpe_main, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (imskpe_main, nb_draw, "nb_draw");
  GLADE_HOOKUP_OBJECT (imskpe_main, draw_freq, "draw_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_draw_freq, "lb_draw_freq");
  GLADE_HOOKUP_OBJECT (imskpe_main, draw_amp, "draw_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_draw_amp, "lb_draw_amp");
  GLADE_HOOKUP_OBJECT (imskpe_main, draw_band, "draw_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, lb_draw_band, "lb_draw_band");
  GLADE_HOOKUP_OBJECT (imskpe_main, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (imskpe_main, sb_file, "sb_file");
  GLADE_HOOKUP_OBJECT (imskpe_main, sb_add, "sb_add");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_main, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (imskpe_main), accel_group);

  return imskpe_main;
}

GtkWidget*
create_imskpe_colorsel (void)
{
  GtkWidget *imskpe_colorsel;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkWidget *help_button1;
  GtkWidget *color_selection1;

  imskpe_colorsel = gtk_color_selection_dialog_new (_("Select Color"));
  gtk_window_set_modal (GTK_WINDOW (imskpe_colorsel), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (imskpe_colorsel), FALSE);

  ok_button1 = GTK_COLOR_SELECTION_DIALOG (imskpe_colorsel)->ok_button;
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_COLOR_SELECTION_DIALOG (imskpe_colorsel)->cancel_button;
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  help_button1 = GTK_COLOR_SELECTION_DIALOG (imskpe_colorsel)->help_button;
  GTK_WIDGET_SET_FLAGS (help_button1, GTK_CAN_DEFAULT);

  color_selection1 = GTK_COLOR_SELECTION_DIALOG (imskpe_colorsel)->colorsel;
  gtk_widget_show (color_selection1);
  gtk_color_selection_set_has_opacity_control (GTK_COLOR_SELECTION (color_selection1), FALSE);

  g_signal_connect ((gpointer) imskpe_colorsel, "destroy_event",
                    G_CALLBACK (on_imskpe_colorsel_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) ok_button1, "clicked",
                    G_CALLBACK (on_ok_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button1, "clicked",
                    G_CALLBACK (on_cancel_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) color_selection1, "configure_event",
                    G_CALLBACK (on_color_selection1_configure_event),
                    NULL);
  g_signal_connect ((gpointer) color_selection1, "color_changed",
                    G_CALLBACK (on_color_selection1_color_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_colorsel, imskpe_colorsel, "imskpe_colorsel");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_colorsel, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_colorsel, cancel_button1, "cancel_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_colorsel, help_button1, "help_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_colorsel, color_selection1, "color_selection1");

  return imskpe_colorsel;
}

GtkWidget*
create_imskpe_file (void)
{
  GtkWidget *imskpe_file;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;

  imskpe_file = gtk_file_selection_new (_("Select File"));
  gtk_container_set_border_width (GTK_CONTAINER (imskpe_file), 12);

  ok_button2 = GTK_FILE_SELECTION (imskpe_file)->ok_button;
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);

  cancel_button2 = GTK_FILE_SELECTION (imskpe_file)->cancel_button;
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) ok_button2, "clicked",
                    G_CALLBACK (on_ok_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button2, "clicked",
                    G_CALLBACK (on_cancel_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_file, imskpe_file, "imskpe_file");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_file, ok_button2, "ok_button2");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_file, cancel_button2, "cancel_button2");

  return imskpe_file;
}

GtkWidget*
create_imskpe_about (void)
{
  GtkWidget *imskpe_about;
  GtkWidget *dialog_vbox1;
  GtkWidget *about_label;
  GtkWidget *dialog_action_area1;
  GtkWidget *bn_about_credits;
  GtkWidget *alignment1;
  GtkWidget *hbox4;
  GtkWidget *image1;
  GtkWidget *label5;
  GtkWidget *bn_about_close;

  imskpe_about = gtk_dialog_new ();
  gtk_widget_set_size_request (imskpe_about, 330, 200);
  gtk_window_set_title (GTK_WINDOW (imskpe_about), _("About"));

  dialog_vbox1 = GTK_DIALOG (imskpe_about)->vbox;
  gtk_widget_show (dialog_vbox1);

  about_label = gtk_label_new (_("\n\n\nimskpe \n\n\n\n\n(c) 2004 by Andreas Madsack"));
  gtk_widget_show (about_label);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), about_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (about_label), GTK_JUSTIFY_CENTER);

  dialog_action_area1 = GTK_DIALOG (imskpe_about)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_EDGE);

  bn_about_credits = gtk_button_new ();
  gtk_widget_show (bn_about_credits);
  gtk_dialog_add_action_widget (GTK_DIALOG (imskpe_about), bn_about_credits, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (bn_about_credits, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (bn_about_credits), alignment1);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox4);

  image1 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox4), image1, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Credits"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  bn_about_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (bn_about_close);
  gtk_dialog_add_action_widget (GTK_DIALOG (imskpe_about), bn_about_close, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (bn_about_close, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) bn_about_close, "clicked",
                    G_CALLBACK (on_bn_about_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_about, imskpe_about, "imskpe_about");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_about, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (imskpe_about, about_label, "about_label");
  GLADE_HOOKUP_OBJECT_NO_REF (imskpe_about, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (imskpe_about, bn_about_credits, "bn_about_credits");
  GLADE_HOOKUP_OBJECT (imskpe_about, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (imskpe_about, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (imskpe_about, image1, "image1");
  GLADE_HOOKUP_OBJECT (imskpe_about, label5, "label5");
  GLADE_HOOKUP_OBJECT (imskpe_about, bn_about_close, "bn_about_close");

  return imskpe_about;
}

